import assert from "node:assert/strict";
import { readFileSync, statSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(resolve(root,"package.json"),"utf8"));
const market = JSON.parse(readFileSync(resolve(root,".agents/plugins/marketplace.json"),"utf8"));
assert.equal(pkg.version,"0.7.2"); assert.equal(market.name,"eeaker-grok"); assert.equal(market.plugins.length,1);
const pluginRoot=resolve(root,market.plugins[0].source.path); const manifest=JSON.parse(readFileSync(resolve(pluginRoot,".codex-plugin/plugin.json"),"utf8"));
assert.equal(manifest.version,pkg.version); assert.equal(manifest.mcpServers,"./.mcp.json");
const mcp=JSON.parse(readFileSync(resolve(pluginRoot,".mcp.json"),"utf8")).mcpServers.grok_subagent;
assert.equal(mcp.tool_timeout_sec,1860); assert.equal(mcp.enabled_tools.length,11);
for (const name of mcp.enabled_tools) assert.ok(mcp.tools[name].output_token_limit>0);
assert.equal(mcp.tools.grok_spawn_worker.approval_mode,"prompt");
for (const path of ["mcp-server/server.mjs","scripts/run_search.py","agents/readonly.md","agents/worker.md","skills/grok-subagent/SKILL.md"]) assert(statSync(resolve(pluginRoot,path)).isFile());
for (const path of ["install.ps1","install.sh","scripts/doctor.mjs","benchmark/summarize.mjs","SECURITY.md","ARCHITECTURE.md"]) assert(statSync(resolve(root,path)).isFile());
const server=readFileSync(resolve(pluginRoot,"mcp-server/server.mjs"),"utf8"); assert.match(server,/const VERSION = "0\.7\.2"/); assert.doesNotMatch(server,/function persistIsolatedAuth/); assert.match(server,/resolveWaitSeconds/); assert.match(server,/securityContract/);
const search=readFileSync(resolve(pluginRoot,"scripts/run_search.py"),"utf8"); assert.doesNotMatch(search,/_persist_refreshed_auth/); assert.match(search,/LOCALAPPDATA/); assert.match(search,/taskkill/);
const cleanup=readFileSync(resolve(root,"scripts/cleanup-codex-config.py"),"utf8");
assert.match(cleanup,/enabled = false/);
assert.match(cleanup,/migrate_plugin_identity/);
assert.match(cleanup,/eeaker-grok/);
console.log("0.7.2 repository layout is valid.");
